### PR TITLE
feat: using base module contract to reduce LoC of reused code

### PR DESCRIPTION
**Pull request by zeroknots**
I compartmentalized code that is reused across module flavors into a module base. 
this should reduce LoC for the audit

### CODE REVIEW

**Comment by JohnGuilding** [comment]
Nice, thanks for trying this out. I'm currently 50/50 on this idea.

On one hand, it does consolidate common logic so it is only written once. On the other hand, I compared these changes to the original module, and LOC are actually a little higher than the current change (guess from the extra boilerplate of base module and not being a huge amount of logic to abstract in terms of LOC in the first place).

@wshino @SoraSuegami wdyt? I think the question I'm trying to answer is is this extra abstraction worth any potential saving from audit cost

**Comment by wshino** [comment]
@JohnGuilding If we plan to create various modules in the future by inheriting from the base module, then this change makes sense.
Are there any real plans to add more modules in the near future? Sorry I am not sure about the future plans.

**Comment by Divide-By-0** [comment]
Less code duplication and cleaner code is good. Don't work about audit cost increases, it's not really substantial or worth factoring in. I would much rather have better code than an easier audit. On the other hand, increasing simplicity is a fine reason to reduce LoC but that doesn't seem to be the case here.

**Comment by JohnGuilding** [comment]
I'm leaning towards keeping things as they are. 

The base module does increases code reuse, but leads to more LOC (extra boilerplate from base module not being offset from reused logic) and increased abstraction. And IMO we should avoid inheritance if it doesn't have a strong benefit

Let me know if anyone disagrees

**Pull request closed without merging**
